### ISSUE TITLE
feature request: is it possible to have giticons with nerd fonts? Something similar to nvim tree's implementation maybe?

### ISSUE THREAD

**Issue by samrath2007** [luukvbaal/nnn.nvim#1]

**Comment by luukvbaal** [comment]
I have a version of the patch that can print icons but I'm not sure how to implement it.

I would like to maintain all the information represented by the dual columns of `git status --porcelain` but I can't really find single width icons that will look good next to each other.
Any suggestions are welcome @samrath2007 @n3born
![image](https://user-images.githubusercontent.com/31730729/140071035-f1aa63cd-0de3-42d7-9ccb-11f49542c738.png)

**Comment by luukvbaal** [comment]
New version of the gitstatus patch shows nerd icons when built with `O_NERD=1`: https://github.com/jarun/nnn/pull/1220
