### ISSUE TITLE
Explorer Won't Select Files

### ISSUE THREAD

**Issue by LennyPhoenix** [luukvbaal/nnn.nvim#103]
For some reason on my setup, using the explorer mode and pressing enter on a file won't open it.

Worth noting that the picker mode works perfectly.

I've tested disabling all my plugins and options to the same effect.

Note that I'm using this in my `.zshrc` to change the pwd on nnn exit. Should I use a more explicit `cmd` parameter in my `nnn.nvim` setup config?

```zsh
nnn ()
{
    if [[ "${NNNLVL:-0}" -ge 1 ]]; then
        echo "nnn is already running"
        return
    fi

    export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"

    command nnn "$@"

    if [ -f "$NNN_TMPFILE" ]; then
        . "$NNN_TMPFILE"
        rm -f "$NNN_TMPFILE" > /dev/null
    fi
}

```

**Comment by LennyPhoenix** [comment]
I've tried setting the explorer's `cmd` to `/bin/nnn` to no effect.

**Comment by luukvbaal** [comment]
Are you overwriting `NNN_FIFO` like in #97?

**Comment by LennyPhoenix** [comment]
I've got "-a" set for tui-preview in `NNN_OPTS`, that'd do it :sweat_smile:

**Comment by LennyPhoenix** [comment]
Fixed by moving "a" out of NNN_OPTS, adding it to my `nnn` alias in `.zshrc` and making sure the `cmd` flag in nnn.nvim is set to `/bin/nnn`
