### ISSUE TITLE
Feature Request: Replace netrw if the first argument of vi is a directory

### ISSUE THREAD

**Issue by f3fora** [luukvbaal/nnn.nvim#12]
`netrw`, the default file explorer of vim, can be disable with

```lua
vim.g.loaded_netrw = 1
vim.g.loaded_netrwPlugin = 1
```
I would like to open `NnnPicker` or `NnnExplorer` when Vim starts with a directory argument, in a similar way of [NERDtree](https://github.com/preservim/nerdtree/blob/eed488b1cd1867bd25f19f90e10440c5cc7d6424/README.markdown?plain=1#L150-L155).

The option `replace_netrw = picker/explorer,` open a sort of non-interactive window, which is not usable.

Thanks

**Comment by luukvbaal** [comment]
You need to set `replace_netrw` to either `"picker"` or `"explorer"`, also mind the quotes as it's supposed to be a string. Does that work for you?

**Comment by f3fora** [comment]
> You need to set `replace_netrw` to either `"picker"` or `"explorer"`, also mind the quotes as it's supposed to be a string.

of course!

> Does that work for you?

Yes, but not how I expect. It took some times to understand how it works! 

- The focus is not on the nnn window and so I need to change it.
- The window is not interactive! I need to press some random combination of `i` and `enter` to make it works.

**Comment by luukvbaal** [comment]
Does https://github.com/luukvbaal/nnn.nvim/commit/b173e74da5ae153b3995e73bd3a09c790a1270e8 improve the behavior at all?

**Comment by f3fora** [comment]
Yes! Now it works perfectly! 

Thanks!

**Comment by luukvbaal** [comment]
Thanks for reporting!
