### ISSUE TITLE
picker with preview - always open in home dir.

### ISSUE THREAD

**Issue by JoseConseco** [luukvbaal/nnn.nvim#19]
Using picker - 'tmux new-session nnn -P u' always starts in home directory. 
Expected result:  nnn picker should open in current file dir.
Changing back to `cmd='nnn -G -C`  will open nnn in current file dir (or is it project dir) . 
I hope someone can confirm.

**Comment by JoseConseco** [comment]
Also - when using nnn without preview - q will close picker with poupu. But with picker enabled I have to press q twice - once to close main window, then to close preview, then ctrl+d to kill/close the  nnn popup.

**Comment by luukvbaal** [comment]
To start nnn in the directory of the current directory, run with `%:p:h` as argument i.e. `NnnPicker %:p:h` (see [README](https://github.com/luukvbaal/nnn.nvim#bindings)).

> Also - when using nnn without preview - q will close picker with poupu. But with picker enabled I have to press q twice - once to close main window, then to close preview, then ctrl+d to kill/close the nnn popup.

This is due to a race condition described in https://github.com/jarun/nnn/pull/1189#issuecomment-933029985.

You can try if adding a small `sleep` to the beginning of `winch_handler()` in `preview-tui` helps, I think `sleep 0.4` fixed it in my case but you might be able to go lower depending on your system.

Of course adding this `sleep` to `winch_handler` will delay resizing image previews which is why I hadn't pushed it yet, still looking for a proper fix.

**Comment by JoseConseco** [comment]
Ok I think I got it to work. Just note for other people facing similar issues. Lua mapping:
```lua
vim.api.nvim_set_keymap( "n", "<F4>", "<Cmd>NnnPicker %:p:h<CR>", { noremap = true, silent = true} )
```
Wont work on directories that contain space in name (nnn will just blink). For 'normal' folder it will display nnn - with preview.
Using vim.cmd works ok though  (with preview and in folder with spaces too):
```lua
 vim.cmd([[nnoremap <F4> <cmd>NnnPicker<CR>]])
```

Also interesting - I'm using system shortcut key for running nvim in terminal ( `alacritty -e sh -c "sleep 0.1 && nvim"`) , this makes nnn preview missing (even if using vim.cmd() mapping - and adding sleep to `winch_handler()` ) . 
The optimal way to run nnn with preview is to use `vim.cmd()` for mapping, and running  nvim manually from command line. Then nnn will work in folders with spaces, and it will show previews, and q-key will close nnn popup correctly.

**Comment by luukvbaal** [comment]
Please check if https://github.com/luukvbaal/nnn.nvim/commit/6e6b690accf8cdc7d560b032ada60cc4bdd06fbf fixes your issues with directories containing spaces.

**Comment by luukvbaal** [comment]
I'm not sure I understand the problem you're describing with your system shortcut key.
What does nnn preview missing mean?

**Comment by JoseConseco** [comment]
The spaces in file path issue is solved - I can see nnn even when running nvim from hotkey.    About missing previews.
Running nnn when  nvim was opened from system shorcut:
![image](https://user-images.githubusercontent.com/13521338/140725448-86dd1a8d-deba-49be-99ca-a86eaa31189b.png)

Running nnn when nvim was opened manually  (first open terminal, then type in 'nvim'):n
![image](https://user-images.githubusercontent.com/13521338/140726410-19349cf3-4dc1-401d-93c7-5d8269bff6c3.png)

I'm not sure why the UI style is so different  between running nnn  'manually' and from shortcut.

**Comment by JoseConseco** [comment]
Now I think I may have two versions in nnn installed, and each of them is executed - depending on how nvim was started. I will check it out.

**Comment by luukvbaal** [comment]
I suspect this is because you run `sh -c 'sleep 0.1 && nvim` (why?). Probably `NNN_PLUG` is not set in your `sh` environment, but is set in your regular shell environment.

**Comment by JoseConseco** [comment]
sleep  supposed to  help make nvim window size match alacritty terminal size when running from hotkey. Otherwise often nvim would take half screen of terminal size. 
Ok i can see that `:!env  | grep NNN` is empty when executed from nvim that what started from hotkey (nvim started manually can see NNN env variables) . I'm not sure where should  I setup additional NNN variables.
I tried:
![image](https://user-images.githubusercontent.com/13521338/140729966-598b59c9-ea23-40e5-b740-487dfbb7305c.png)
maybe missing NNN variables in local tmux  is the source of problem?  Sorry for so many questions, and thanks for your time.

**Comment by luukvbaal** [comment]
Please check if https://github.com/luukvbaal/nnn.nvim/commit/5e4cb0fdc4802106deea61d77f4196abff27aa96 fixes your terminal size issue without the `sleep` (and `sh -c`).

**Comment by JoseConseco** [comment]
@luukvbaal Maybe I was not clear  - the `sleep` in `alacritty -e sh -c "sleep 0.1 && nvim"` has nothing to do with nnn picker.  It is workaround for nvim window not taking full space of alacrity terminal window.  
It just so happens, that when running nvim using above command from system shortcut,  then opening  nnn picker does now give previews  (but is caused by missing env variables as you pointed out). 
Somehow nvim sees or does not see env variables, depending on how it was started.

**Comment by luukvbaal** [comment]
Alright, there was a bug in the `win_resized` function though so picker window resizing was not working in general.

Regarding your env, I would try to use the `-c` flag of your regular shell. So instead of `sh -c '...'`, `zsh -c '...'` or `bash -c`.

**Comment by JoseConseco** [comment]
Thanks - changing sh - zsh did the trick. Weird since I had defined  NNN variables in both zsh and bash, but whatever works. 
Closing

**Comment by luukvbaal** [comment]
@JoseConseco with https://github.com/jarun/nnn/pull/1226 merged you should be able to remove the `sleep` from `winch_handler`.

Test it out and confirm if you can

**Comment by JoseConseco** [comment]
All works great.  Btw after yesterday fight with env vars   tmux envs  were reset.  I'm not sure why they wont save correctly after restart. But command works:
```lua
picker={ cmd="tmux new-session -e NNN_FIFO=/tmp/nnn.fifo.preview -e NNN_PLUG='p:preview-tui;f:fzcd;o:fzopen;d:diffs' nnn -Pp -G -C -d " }, -- with -G git, -d details
```
-e   -> lets you set env variable for session.

**Comment by luukvbaal** [comment]
Thanks for confirming.

Yeah that is a weird way to set your environment but whatever works for you 🤷🏻‍♂️
