### ISSUE TITLE
Mappings don't work on hovered file in picker mode

### ISSUE THREAD

**Issue by amanjitsk** [luukvbaal/nnn.nvim#21]
Hi,
So I just found this plugin, and it works better than the [nnn.vim](https://github.com/mcchrish/nnn.vim) plugin for me.
However, the custom mappings (aside from enter) do not work for the picker, where there is no selection (i.e. on the hovered file).
The other plugin works as expected in this case.
Here are my settings:
```vim
lua << EOF
local builtin = require("nnn").builtin
local cfg = {
	explorer = {
		cmd = "nnn",       -- command overrride (-F1 flag is implied, -a flag is invalid!)
		width = 40,        -- width of the vertical split
		side = "topleft",  -- or "botright", location of the explorer window
		session = "local",      -- or "global" / "local" / "shared"
		tabs = true,       -- seperate nnn instance per tab
	},
	picker = {
		cmd = "nnn",       -- command override (-p flag is implied)
		style = {
			width = 0.7,     -- width in percentage of the viewport
			height = 0.7,    -- height in percentage of the viewport
			xoffset = 0.5,   -- xoffset in percentage
			yoffset = 0.5,   -- yoffset in percentage
			border = "rounded" -- border decoration for example "rounded"(:h nvim_open_win)
		},
		session = "shared",      -- or "global" / "local" / "shared"
	},
	auto_open = {
		setup = nil,       -- or "explorer" / "picker", auto open on setup function
		tabpage = nil,     -- or "explorer" / "picker", auto open when opening new tabpage
		empty = false,     -- only auto open on empty buffer
		ft_ignore = {      -- dont auto open for these filetypes
			"gitcommit",
		}
	},
	auto_close = true,  -- close tabpage/nvim when nnn is last window
	replace_netrw = "explorer", -- or "explorer" / "picker"
	mappings = {
		{ "<C-t>", builtin.open_in_tab },       -- open file(s) in tab
		{ "<C-s>", builtin.open_in_split },     -- open file(s) in split
		{ "<C-v>", builtin.open_in_vsplit },    -- open file(s) in vertical split
		{ "<C-p>", builtin.open_in_preview },   -- open file in preview split keeping nnn focused
		{ "<C-y>", builtin.copy_to_clipboard }, -- copy file(s) to clipboard
		{ "<C-w>", builtin.cd_to_path },        -- cd to file directory
		{ "<C-e>", builtin.populate_cmdline },  -- populate cmdline (:) with file(s)
	},
	windownav = {        -- window movement mappings to navigate out of nnn
		left = "<C-w>h",
		right = "<C-w>l"
	},
}
require("nnn").setup(cfg)
EOF
```
For example, if I were to press `<C-v>` on a hovered file in the picker (no selection), it should just 
open the hovered file in a vertical split. But it simply exits (without opening the hovered file) when I do that.

**Comment by luukvbaal** [comment]
Hi, great to hear that it's working better for you than nnn.vim. I really tried to work out all the kinks.

To use the mappings in picker mode you need to first select a file in `nnn` (e.g. press <kbd>Space</kbd>), followed by your mapping. Does it work without selecting first in nnn.vim? I'll check if it makes sense to make that standard behavior.

**Comment by amanjitsk** [comment]
Yup selecting the file first works. But I am used to just executing the keybind on the hovered file (this is also the standard behavior in the other plugin). Its also just a bit odd to select a single file (adds an extra step, when the behavior can just be applied to the hovered file). In the other plugin, when a selection exists, it just opens that (so that way, you won't need to prompt the user in case of existing selection - it should just be prioritized over hovered)

**Comment by luukvbaal** [comment]
I think I differentiated both cases due to the old behavior but since https://github.com/jarun/nnn/commit/24b71bcf1f36661216e73d5211cab2226e126705 it definitely makes more sense to als open with <kbd><Enter</kbd> in picker mode.

Thanks!
