### ISSUE TITLE
nnn reverse layout on the screenshot

### ISSUE THREAD

**Issue by anuvyklack** [luukvbaal/nnn.nvim#24]
How do you get this reverse layout of detailed view like on the screenshot in the preview-tui section in the README? 
The `nnn -d` gives me a layout like `ls -l` with the name at the end of the line.

**Comment by luukvbaal** [comment]
This is nnn with the [namefirst](https://github.com/jarun/nnn/blob/master/patches/namefirst/mainline.diff) patch.

To use this layout you will need to compile nnn yourself with the `O_NAMEFIRST=1` make flag.

**Comment by anuvyklack** [comment]
Thank you!
