### ISSUE TITLE
[Bug] Open file can not return to nnn

### ISSUE THREAD

**Issue by chriztheanvill** [luukvbaal/nnn.nvim#25]
Hi.

- Launching nnn picker
- Trying to "Open with" 
- Do not insert nothing, then press enter

![image](https://user-images.githubusercontent.com/37992958/142989083-5579869f-5528-4ca4-b73f-81d7f714eb0c.png)

![image](https://user-images.githubusercontent.com/37992958/142989112-f0316483-59e2-451a-af77-5f679301dac6.png)

Check the bottom of the image, I can not close nnn, or use it.
![image](https://user-images.githubusercontent.com/37992958/142989248-656ab1c9-7326-4def-96bb-7a7248857b86.png)

 
nnn does not close or return to nnn

**Comment by luukvbaal** [comment]
Should be fixed by the mentioned PR.
