### ISSUE TITLE
Icons not showing in vim

### ISSUE THREAD

**Issue by amanjitsk** [luukvbaal/nnn.nvim#27]
Hi,
I have the icons working successfully in terminal nnn,
but for some reason the icons do not display when using
nnn in nvim. Here is a screenshot:
![image](https://user-images.githubusercontent.com/12499495/143170569-cd1ca8c7-e7de-442a-9669-0e87101b0a0d.png)
I am certain this has to do with enabling 256 color support in neovim,
but can't quite figure it out. Any directions would be helpful!
Thanks,
Amanjit

**Comment by luukvbaal** [comment]
I can reproduce this by setting LANG to a non-UTF.8 value i.e.

    LANG=en_US nvim

vs

    LANG=en_US.UTF-8 nvim

Please check if the locale detected by your neovim environment is somehow not ending in `.UTF-8`.

**Comment by amanjitsk** [comment]
Found it, I was actually setting `let $LANG = en` in my vimrc, but my shell was correctly set.
Thanks!
