### ISSUE TITLE
Bookmarks not displaying when using a GUI client

### ISSUE THREAD

**Issue by medwatt** [luukvbaal/nnn.nvim#29]
I have recently been playing with neovim GUI clients like neovide and noticed that pressing `b` (to get the bookmarks menu) does not work. However, if I open a terminal (`:term`) and launch `nnn` inside the terminal, `b` works. Any idea why this might be happening?

**Comment by luukvbaal** [comment]
I presume you're setting your `NNN_BMS` inside your shell environment which gets picked up by `:term`:. Try setting your nnn environment variables in your login shell profile (`.profile`/`.zprofile`) instead and it should work.
