### ISSUE TITLE
If i open NnnPicker and then close it, the statusline is messed up.

### ISSUE THREAD

**Issue by hrqmonteiro** [luukvbaal/nnn.nvim#3]
https://user-images.githubusercontent.com/17055027/136293218-4ac197f1-b864-4b0f-a85b-b57480713cdc.mp4

And also, NnnExplorer doent work. It opens but i have an error. And none of the files open if i click enter on it.

https://user-images.githubusercontent.com/17055027/136293368-c1b3c6ff-f935-48f3-864e-413852b97295.mp4

Here i clicked enter or double click on the file and it just won't open.

**Comment by luukvbaal** [comment]
You will get that error if `nnn` is started with the `-a` flag. The plugin removes `a` from the `NNN_OPTS` environment variable but you might have added it yourself to the `cmd` override?

I'll see if I can improve the docs to discourage adding it or mention it with error detection.

**Comment by jonasstr** [comment]
I got a similar error as @hrqmonteiro when calling `:NnnExplorer` (the drawer on the side does not even get show up) - maybe it has to do with the `/tmp/nvimsSEKVQ`directory name. 
```lua
Error executing luv callback:                                                                   
...l/share/nvim/site/pack/packer/start/nnn.nvim/lua/nnn.lua:87: Error opening pipe for reading:E
NOENT: no such file or directory: /tmp/nvimsSEKVQ/3-explorer                                    
 Avoid running nnn with the -a flag!     
```
I have freshly installed n^3 using `sudo apt install nnn`. Thanks for any help!

**Comment by luukvbaal** [comment]
Closing due to lack of response, please do let me know if you still have any errors.

**Comment by hrqmonteiro** [comment]
> Hi, thanks for reporting.
> 
> `nnn.nvim` doesn't touch the statusbar so not sure what we can do here. My statusbar([feline](https://github.com/famiu/feline.nvim)) also hides when I open `NnnPicker` but the statusline is restored when `NnnPicker` is toggled/closed.
> 
> > And also, NnnExplorer doent work. It opens but i have an error. And none of the files open if i click enter on it.
> 
> Are you using a custom `cmd` override and or `NNN_OPTS`? If so could you share those. Haven't been able to reproduce the error.
> 
> Can confirm mouse support is not working in the explorer split though, I'll look into that, not sure if it's possible though. Mouse pass-through seems to work in floating windows but can't find anything on enabling it in regular splits.

I was using NNN_OPTS but i cleared it all, and i removed any passable flags of nnn i had, and i am still having the same error when opening NnnExplorer, even after i updated

![nnn](https://user-images.githubusercontent.com/17055027/136769173-6630079f-3ac5-465f-bba4-f3e579515b14.png)

And i am using `galaxyline.nvim`, and the statusline is still being messed after i close `NnnPicker`. Didnt try with feline though cause i dont have a config for that.

**Comment by luukvbaal** [comment]
What version on `nnn`  and `neovim` are you on?
Does pressing ENTER on that message give you any more errors?

**Comment by hrqmonteiro** [comment]
> Could you check if latest commit fixes the issue?

Hi, i updated.

It stills behaves the same way.

I realized that if i use Bash instead of Fish, the `NnnExplorer` issues resolve. I can use the explorer and open files without that ENOENT error.

But the `NnnPicker` messing with galaxyline still occurs.

**Comment by luukvbaal** [comment]
Like I said, that error is expected if nnn.nvim is starting nnn with the `-a` flag somehow I guess that is what must be happening in your fish shell for some reason.

I can't reproduce your statusline issue, tried lualine and galaxyline.

**Comment by luukvbaal** [comment]
The only other possible explanation I can think of is that fish is significantly slower resulting in nnn not having created the fifo yet when read_fifo is being called.

Could you check if [this](https://github.com/luukvbaal/nnn.nvim/tree/mkfifo) branch fixes it?
