### ISSUE TITLE
nnn.nvim vs nnn.vim colors

### ISSUE THREAD

**Issue by ldelossa** [luukvbaal/nnn.nvim#30]
Hey there,

I'm looking at moving from nnn.nvim from nnn.vim. 

I notice that nnn.vim will actually use different colors in the NNN ui then nnn.nvim. 

The colors are more aligned to my color scheme, so they seem to be either picking up on my terminal colors or my Vim color scheme. Anyway to achieve this effect in nnn.nvim?

![image](https://user-images.githubusercontent.com/5642902/144729013-6bad16b0-f0ee-4e8e-ad4d-c25a348b23ff.png)
nnn.nvim ^

![image](https://user-images.githubusercontent.com/5642902/144729022-498f3cb1-39d9-49a6-b1af-f3b84f6f2bc5.png)
nnn.vim ^

**Comment by luukvbaal** [comment]
I suspect you might be using the `-C` flag in your nnn.vim config.

**Comment by ldelossa** [comment]
you're correct! 

```
let g:nnn#command = 'nnn -C'
```

I'll get this applied to nnn.nvim. Thanks for the tip.

**Comment by ldelossa** [comment]
that did it! thanks again.
