### ISSUE TITLE
Using NNN changes what expand('%') returns

### ISSUE THREAD

**Issue by ldelossa** [luukvbaal/nnn.nvim#31]
Hey there,

Not 100% sure this is an issue with NNN but let me describe. 

I'm writing a Neovim plugin which keeps track of file URI's to some degree. 

When vim opens up to a root directory and the "edit" command is used to open a file in that directory, `vim.fn.expand('%')` will return the relative path to that file, something like "file1". 

Now, if within the same Neovim instance you then open file2 with NNN `vim.fn.expand('%')` shows an absolute path to file2. Funny enough if you use NNN to go and open file1, expand still shows the relative path. 

Here is a small video demonstrating that when `edit` command is `expand` returns relative paths and when NnnPicker is used `expand` returns absolute. 

https://user-images.githubusercontent.com/5642902/145226664-698a1024-cfca-4101-9747-f76e100a77ef.mp4

**Comment by luukvbaal** [comment]
This is just a result of `nnn` returning the absolute path which is added to the bufferlist.

> Funny enough if you use NNN to go and open file1, expand still shows the relative path.

I expect this is because vim does not replace the already present file1 in the bufferlist, keeping the relative path.

I'm not sure there's anything to do here, does it lead to any issues for you?

**Comment by luukvbaal** [comment]
You can always get the relative path with `fnamemodify(expand('%'),":~:.")`. Alternatively we could let the plugin add the relative paths to the bufferlist, do you see any benefits in that?

**Comment by ldelossa** [comment]
> You can always get the relative path with `fnamemodify(expand('%'),":~:.")`. Alternatively we could let the plugin add the relative paths to the bufferlist, do you see any benefits in that?

This may lead to a more consistent experience, as its what the "edit" command seems to do.

**Comment by luukvbaal** [comment]
Not really, it just depends on whether the argument to edit was a relative or absolute path. I.e. `:edit /home/user/file` will result in `expand('%') -> /home/user/file` as well.

**Comment by luukvbaal** [comment]
I'm not sure it would be an improvement to make this plugin add the relative path to the buffer list. 

Unless you can convince me otherwise, I think it's better left to the user to get the relative path when needed.

**Comment by ldelossa** [comment]
Fair enough
