### ISSUE TITLE
How to cd to empty directory?

### ISSUE THREAD

**Issue by spareslant** [luukvbaal/nnn.nvim#33]
Hi,
Thanks for this plugin.

looking at this 
```
{ "<C-w>", builtin.cd_to_path },        -- cd to file directory
```

How to change directory which is empty or directory containing just directories (not regular file) using `C-w`?  This works only when directory has at least a regular file.

**Comment by luukvbaal** [comment]
We rely on getting the path from `nnn` through selecting a file by pressing <kbd>Enter</kbd>. This does nothing in an empty directory.

This is unfortunately a limitation of the custom mapping implementation. I don't see a way around it.

**Comment by spareslant** [comment]
I managed to make it working, but process is not intuitive. 
With the following code, directory change can happen in empty directory as well, but for this to work, following steps are to be done.

- launch `nnn` inside nvim.
- select directory in which `cd` has to be done  by pressing `<spacebar>`. This might move the cursor to next directory or file in the current list.
-  now press the key-binding for `cd`.
- If selected directory is empty then you have to quit `nnn` by pressing `q`
- change directory done. (confirmed via `:pwd`)
- If selected directory has a regular file then `nnn` will close automatically.

Following is my change for above to work. Note: I am using `<ATL-w>` key-binding for cd to work.
```lua
local fn = vim.fn
fn.execute("highlight NnnBorder guifg=#555555")

local builtin = require("nnn").builtin

local function is_dir(path)
    f = io.open(path)
    return not f:read(0) and f:seek("end") ~= 0
end

-- while in nnn, use <spacebar> to select directory and then press <A-w> and press q to quit nnn
-- see the bindings below.
function builtin.mycd_to_path(files)
  local dir = is_dir(files[1])
  print("MY-DEBUG => "..files[1])
  local targetDir = ""

  if dir == true
  then
    targetDir = files[1]
  else
    targetDir = files[1]:match(".*/")
  end
  fn.execute("cd "..targetDir)
  vim.defer_fn(function() print("working directory changed to: "..targetDir) end, 0)
end

require("nnn").setup({
	picker = {
    cmd = "nnn -d -G",
		style = { border = "rounded" },
	},
	mappings = {
		{ "<C-t>", builtin.open_in_tab }, -- open file(s) in tab
		{ "<C-s>", builtin.open_in_split }, -- open file(s) in split
		{ "<C-v>", builtin.open_in_vsplit }, -- open file(s) in vertical split
		{ "<C-p>", builtin.open_in_preview }, -- open file in preview split keeping nnn focused
		{ "<C-y>", builtin.copy_to_clipboard }, -- copy file(s) to clipboard
		{ "<A-w>", builtin.mycd_to_path }, -- cd to selected directory
		{ "<C-e>", builtin.populate_cmdline }, -- populate cmdline (:) with file(s)
	},
})
```
