### ISSUE TITLE
Setting to delete buffer when not visible

### ISSUE THREAD

**Issue by gzagatti** [luukvbaal/nnn.nvim#38]
Is there a setting to disable the buffer when it is not visible anymore? I tried several things but none worked:

1. Set the `bufhidden` option to `delete`: even though the option is on and the buffer is hidden it does not get deleted.

2. Add an autocomand `autocmd BufHidden * :lua delete_nnn_hidden()`

    ```lua
          function delete_nnn_hidden()
            local bufnr = vim.fn.bufnr(vim.fn.expand("<afile>:p"))
            if vim.api.nvim_buf_get_option(bufnr, "filetype") ~= "nnn" then return end
            -- TODO figure out how to delete the buffer
            -- as the current command does not currently work
            vim.api.nvim_buf_delete(bufnr, { force = true })
          end
    ```

    Again, the call to `vim.api.nvim_buf_delete(bufnr, { force = true })` does not get rid of the buffer. In fact it does not seem to do anything. When debugging, I added print statements before and after the call to `delete` to make sure the code reaches these sections. Indeed the code reaches these sections.

**Comment by luukvbaal** [comment]
Are you saying you want the nnn buffer to close when you run `NnnExplorer/Picker`? I don't see any reason to. The toggle behavior is intentional and you can just press <kbd>q</kbd> to quit nnn, this will delete the buffer.

**Comment by gzagatti** [comment]
When I run `NnnExplorer` and the `nnn` buffer is open, the window containing the buffer will close but will not delete the buffer.

However, I would like to delete the buffer when it's not visible for the following reasons. 

1. I don't want the `nnn` buffer to be listed in the buffer list when not visible. It's distracting.
2. When I close neovim using the command `:wqa` and the buffer is still open I get the following error: 

    ```vim
    E948: Job still running
    E676: No matching autocommands for acwrite buffer
    ```

3. I prefer to start with a fresh nnn session every time I invoke `NnnExplorer` rather than with the previous session.

**Comment by luukvbaal** [comment]
> 2\. When I close neovim using the command `:wqa` and the buffer is still open I get the following error:

Actually this I forgot this is expected: https://github.com/neovim/neovim/issues/14061.

Try the suggested workarounds.

**Comment by gzagatti** [comment]
Thanks! For (1), which function in `nnn`‘s interna bonding should I call to close the buffer correctly. I’m afraid I couldn’t figure this one out. Then I can write a custom function that toggles `NnnExplorer`: when it’s not visible it will open a new buffer and when open it will close `nnn` and delete the buffer.

**Comment by luukvbaal** [comment]
> which function in `nnn`‘s internal binding should I call to close the buffer correctly

Just press <kbd>Q</kbd>.
