### ISSUE TITLE
FEATURE:bookmark

### ISSUE THREAD

**Issue by jinleileiking** [luukvbaal/nnn.nvim#39]

**Comment by luukvbaal** [comment]
https://github.com/jarun/nnn/wiki/Basic-use-cases#add-bookmarks

**Comment by jinleileiking** [comment]
Need a shortcut key, like nerd:
`B` `d`

**Comment by luukvbaal** [comment]
Bookmarks added as showed in the link can be accessed through <kbd>b ...</kbd>.
