### ISSUE TITLE
nvim_add_user_command

### ISSUE THREAD

**Issue by icher** [luukvbaal/nnn.nvim#40]
Hi there. Just installed nnn.nvim and get error:
```
packer.nvim: Error running config for nnn.nvim: ...l/share/nvim/site/pack/packer/start/nnn.nvim/lua/nnn.lua:528: attempt to call field 'nvim_add_user_command' (a nil value)
```
Looks like your plugin using `nvim_add_user_command` [from Neovim 0.7.0+](https://github.com/nanotee/nvim-lua-guide#defining-user-commands) which is not even released (0.6.1 current latest). With all due respect, do you think it's sane?

**Comment by luukvbaal** [comment]
I indeed thought "sane" 0.6 users would pin the latest commit as the plugin has been stable for months.

Reverted the change and made a 0.7 branch instead to avoid further issues...
