### ISSUE TITLE
Question, How do I get the plugin to jump to a window if it is already open?

### ISSUE THREAD

**Issue by Rofer11607** [luukvbaal/nnn.nvim#41]
I use a lot of side by side windows to view multiple buffers as I edit. Is there a way to get it to jump to an already open window if it is already open?

As a bonus what I would really like to do is define my layout and have it open the buffer in the first window and shift all the other ones down. Is this setup possible with a little config?
example: given 4 buffers - a , b , c ,d in a four square grid layout

![image](https://user-images.githubusercontent.com/55964540/161987621-bf7fa899-c375-41f4-8877-4a44bb4a0ba7.png)

Then I open a buffer 'e' I would like to see the following behavior

![image](https://user-images.githubusercontent.com/55964540/161987805-45cf1a0d-76ed-41c1-89a6-111663c7ba10.png)

The buffer 'd' is then hidden. If the window is already on the screen no change is made and the cursor jumps to the new window. If a new buffer is opened the cursor is moved to the top left quadrant where the new buffer is.

Is this possible? Can someone point me in the right direction?

**Comment by luukvbaal** [comment]
Are you talking about opening nnn in an already open window, or a selected file?
The selected file will open in the last previous active window if available.

All that can be configured for opening NnnExplorer is whether it will open topleft or top botright. For any other layout preferences you would have to edit the plugin.
