### ISSUE TITLE
README with wrong highlight group name

### ISSUE THREAD

**Issue by Yutsuten** [luukvbaal/nnn.nvim#42]
In the session [Colors](https://github.com/luukvbaal/nnn.nvim/blob/9462b759b546efee2646c8f0f765d472399a28cb/README.md?plain=1#L162) in the README, it is written:

> Three highlight groups `NnnNormal`, `NnnNormalNC` and `NnnFloatBorder` are available to configure the colors for the active, inactive and picker window borders respectively.

The group `NnnFloatBorder` does not exist. I looked at the code and the correct group is `NnnBorder`. Could you fix it?

**Comment by Yutsuten** [comment]
Great plugin by the way. Thanks!!

**Comment by luukvbaal** [comment]
Thanks for reporting the issue!
