### ISSUE TITLE
Stop nnn from going/showing into the buffer when toggling nnn

### ISSUE THREAD

**Issue by himanshugoswamiii** [luukvbaal/nnn.nvim#44]
When i toggle nnn, it goes to buffer which **cause problems when i move between my actual files in buffers**. I know i can quit instead of toggling but I don't want to do that because i keep several directories open in nnn contexts (1,2,3,4).

When i toggle [terminal](https://github.com/akinsho/toggleterm.nvim) it doesn't show into the buffer.
 can i make nnn behave like that ?

**Comment by luukvbaal** [comment]
I'm gonna have to ask you to rephrase the problem you're experiencing. I'm not quite sure what you mean.

Please check if the 0.7 branch fixes your problem. I pushed https://github.com/luukvbaal/nnn.nvim/commit/09d772e1d1e88c50413753787297848ebbd39266 which will return focus to the previously active window when toggling.

I think I'll merge 0.7 into master later.

**Comment by himanshugoswamiii** [comment]
Sorry if i didn't make things clear

---
In the first image you can see nnnexplore buffer in the top
![1652045971](https://user-images.githubusercontent.com/96357852/167316902-4db6856c-41e6-4295-b6d6-ee4cbbbe3c84.png)

In the second image my terminal is open but the buffer is not visible
![1652045957](https://user-images.githubusercontent.com/96357852/167316903-32f0d4b0-a8f3-41cb-a867-aae99d980e2e.png)

---
Now look at this:
How i can switch between my files without the terminal buffer interfering in between

https://user-images.githubusercontent.com/96357852/167317249-c47d2828-310a-4f47-b482-613991f4bdcb.mp4

Now suppose i tried to switch buffers quickly when nnn buffer is open i will somehow reach nnn. But i dont want that 

https://user-images.githubusercontent.com/96357852/167317665-ac7e1ffa-6a46-4364-8a08-1a5fe6593c96.mp4

**Is there a way around to make nnn.nvim behave like _toggleterm_**

**Comment by luukvbaal** [comment]
I see, the problem you're describing is more to do with your bufferline plugin. The way I work around this is by adding filetype nnn to my bufferline filter:

```lua
custom_filter = function(buf)
    local ignored = { "nnn", "dap-repl" }
    if not vim.tbl_contains(ignored, vim.api.nvim_buf_get_option(buf, "filetype")) then
        return true 
    end
end,
```

I guess toggleterm is ignored by your statusline config, add nnn to the ignore list to make it behave the same.

**Comment by luukvbaal** [comment]
Actually, we can set `buflisted` to false. I'll provide a config option for it. I think most people would want it to be hidden by default.

**Comment by luukvbaal** [comment]
Latest commit should hide the nnn buffer by default now without needing to hide it in bufferlist config.

**Comment by himanshugoswamiii** [comment]
Thank you !
