### ISSUE TITLE
Error message is displayed if swap file already exists

### ISSUE THREAD

**Issue by ggustafsson** [luukvbaal/nnn.nvim#48]
Hello,

NnnExplorer (but not NnnPicker) displays an error if a file is opened up when a swap file already exists. It does indeed open up the file but it does so while also throwing an exception which is not handled gracefully.

See problem in action here: https://asciinema.org/a/GNk2eQKRPA7x82JaEqDZu5YiX

Best regards,
Göran Gustafsson

**Comment by luukvbaal** [comment]
Thanks for reporting, I'll check out both issues when I get the time.

**Comment by ggustafsson** [comment]
Works great! Thanks! 🙂
