### ISSUE TITLE
Feature Request: Support ^G / NNN_TMPFILE a.k.a. "QuitCD"

### ISSUE THREAD

**Issue by ggustafsson** [luukvbaal/nnn.nvim#53]
Hello!

It would be really great if `nnn.nvim` could support builtin `^G` / `NNN_TMPFILE` in addition to `builtin.cd_to_path`. Basically source last path if file exists after quit.

1. Check if `NNN_TMPFILE` is set. Use `${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd` as fallback.
2. Check if file exists.
3. Read first line and extract second word (path).
4. Run "tcd" or "cd" on path. This should probably be a setting.
5. Delete file.

Similiar to:
- https://github.com/mcchrish/nnn.vim/blob/169951733371abd152d76d1ce65e2dd867156e2d/autoload/nnn.vim#L215
- https://github.com/jarun/nnn/blob/master/misc/quitcd/quitcd.bash_zsh#L22

And related to:
- https://github.com/luukvbaal/nnn.nvim/issues/33

Best regards,
Göran Gustafsson

**Comment by luukvbaal** [comment]
Thanks for the suggestion, please check the fix.

**Comment by ggustafsson** [comment]
Everything checks out! Thanks a lot! 👍

**Comment by kakRostropovich** [comment]
It seems that after this update, NnnPicker started loading with a delay

Check it out, please!

**Comment by luukvbaal** [comment]
See https://github.com/luukvbaal/nnn.nvim/issues/71#issuecomment-1304322107 for a breaking change regarding quitcd.
