### ISSUE TITLE
Built-in actions not working

### ISSUE THREAD

**Issue by anjerukare** [luukvbaal/nnn.nvim#58]
Hello, I faced a problem with the built-in actions.
Executing an action turns the Nnn window into a normal buffer. In the case of NnnPicker, the window doesn't close and no action occurs.

Here is a screencast of this behavior:

https://user-images.githubusercontent.com/81213838/175826780-a509209a-8644-41b0-aabd-2442660829b8.mov
1. Trying to <kbd>Ctrl</kbd>+<kbd>T</kbd> on `flutter-tools.lua`: it turns floating window in normal buffer;
2. Trying same on `autocompletion.lua` - same here;
3. Trying select `autopairs.lua` with <kbd>Space</kbd> and then press <kbd>Ctrl</kbd>+<kbd>T</kbd> - nothing changes.

Also I reproduce it in NnnExplorer and with `open_in_split`, `open_in_vsplit` actions - got the same problem.

My configurations:
<details>
  <summary>nnn.nvim</summary>
  
  
  ```lua
  local builtin = require("nnn").builtin

  -- Nnn setup
  require('nnn').setup {
    replace_netrw = 'picker',
    mappings = {
      { "<C-t>", builtin.open_in_tab },     -- open file(s) in tab
      -- { "<C-s>", builtin.open_in_split },   -- open file(s) in split
      -- { "<C-v>", builtin.open_in_vsplit },  -- open file(s) in vertsplit
    }
  }
  ```
</details>
<details>
  <summary>.bashrc</summary>
  
  ```bash
  # Nnn configuration
export NNN_OPTS='eR'
export NNN_COLORS='#a8a8a8a8'
export NNN_FCOLORS='a8a8a8fbfbfbfbfbfbfbfbfb'
export NNN_FIFO='/tmp/nnn.fifo'
export NNN_PLUG='f:autojump'
eval "$(jump shell bash --bind=f)"
t ()
{
    # Block nesting of nnn in subshells
    if [ -n $NNNLVL ] && [ "${NNNLVL:-0}" -ge 1 ]; then
        echo "nnn is already running"
        return
    fi

    export NNN_TMPFILE="${XDG_CONFIG_HOME:-$HOME/.config}/nnn/.lastd"

    nnn "$@"

    if [ -f "$NNN_TMPFILE" ]; then
            . "$NNN_TMPFILE"
            rm -f "$NNN_TMPFILE" > /dev/null
    fi
}
  ```
</details>

**Comment by luukvbaal** [comment]
Works fine on my end. What's happening in your gif is that instead of executing the nnn mapping is that you're leaving terminal mode. Do you have any conflicting mappings to leave terminal mode?

**Comment by anjerukare** [comment]
I didn't map keys to exit terminal mode.

Here is my `:tmap` output:
`t  ,t          * <Cmd>NnnPicker<CR>`

Even if I disable this remapping, have the same problem.

**Comment by luukvbaal** [comment]
Then the it would seem the feedkeys part of `handle_mapping()` is not working properly on your end, I have no idea why.
https://github.com/luukvbaal/nnn.nvim/blob/dc6c5253a5822e2199d7bac318c38a63cfa189ac/lua/nnn.lua#L368

**Comment by luukvbaal** [comment]
Great, thanks for reporting back. Doest the following diff fix the issue with your usual config?
```diff
diff --git a/lua/nnn.lua b/lua/nnn.lua
index 4e3eb36..b74c02e 100644
--- a/lua/nnn.lua
+++ b/lua/nnn.lua
@@ -194,7 +194,7 @@ local function on_stdout(_, data, _)
 end

 local function feedkeys(keys)
-       api.nvim_feedkeys(api.nvim_replace_termcodes(keys, true, true, true), "m", true)
+       api.nvim_feedkeys(api.nvim_replace_termcodes(keys, true, true, true), "n", true)
 end

 local function buffer_setup(mode, tab)
```

**Comment by luukvbaal** [comment]
I think it should, do let me know if it doesn't.

**Comment by anjerukare** [comment]
It works! Thanks a lot!
