### ISSUE TITLE
Running picker from startify menu

### ISSUE THREAD

**Issue by medwatt** [luukvbaal/nnn.nvim#6]
I use the startify plugin to list folders, sessions, and recently edited files. If I run `NnnPicker` (immediately after launching neovim), and select a file from nnn, the file opens in neovim, but the picker floating window doesn't close. [This](https://i.imgur.com/chrncuV.png) is how it looks.

**Comment by luukvbaal** [comment]
Should be fixed in https://github.com/luukvbaal/nnn.nvim/commit/57d0e558af4f0a8c4556520872f24bcd3fc62775.
