### ISSUE TITLE
Open NnnExplorer as a single window when replacing netrw

### ISSUE THREAD

**Issue by anjerukare** [luukvbaal/nnn.nvim#61]
I want to use `NnnExplorer` as netrw replacement without buffer window in vertical split.
It may seem that I can achieve this with nnn itself, but I want to keep the `cwd`.

Is there any way to do this?

**Comment by luukvbaal** [comment]
So you want `NnnExplorer` to open inside the current window when editing a directory buffer, without splitting? I think this makes sense. Thanks for the suggestion I'll look into it.

I think it could be default behavior when the only window has no active buffers. Would that cover your use case? Or do you want to be able to open in the current window despite the current window already displaying a non-empty buffer?

**Comment by anjerukare** [comment]
> I think it could be default behavior when the only window has no active buffers. Would that cover your use case?

Yes, it would.

> Or do you want to be able to open in the current window despite the current window already displaying a non-empty buffer?

I usually use `NnnPicker` and can't say for sure if anyone will need this behavior.
To be able to open nnn in the current window, it should be enough to use `NnnPicker`.

**Comment by WieeRd** [comment]
How about making a new command for this?  
A command that opens `NnnPicker` inside the current window.  
That would be a drop-in replacement for netrw's `:Explore` command.  
Other netrw commands like `:Vexplore` can be emulated using this as well.

**Comment by luukvbaal** [comment]
@anjerukare @WieeRd please check if https://github.com/luukvbaal/nnn.nvim/commit/0fcc15a3c84d9d6de2ee0057bbcfb59386bf63ec covers your use case. Otherwise, I think indeed allowing to open `NnnPicker` inside the current window makes sense.

**Comment by anjerukare** [comment]
@luukvbaal, sorry for late response. It covers my case, kind of.
I would like `NnnExplorer` to behave even more like netrw.

Here is my use case with netrw:

https://user-images.githubusercontent.com/81213838/185424477-8cff2830-58c1-4909-bb9d-52e9bb6837e7.mov

Same use case with `NnnExplorer`:

https://user-images.githubusercontent.com/81213838/185424556-af90a6b6-2683-406a-9932-d770994bb6e5.mov

- After entering the file I have a splitted `NnnExplorer`. It's fine for `NnnExplorer` users, but I don't need it because I am using `NnnPicker`.
- To get back to the terminal, I have to do a sequence of actions: `:q`, press <kbd>q</kbd> in `NnnExplorer` and `:q`.

I also found that when I set `width = 1` and `height = 1` for `NnnPicker` I get a clean and usable result:

https://user-images.githubusercontent.com/81213838/185428795-ca28726d-d79b-43bb-9f8d-4d088bb8046c.mov

But, of course, I don't want to have a "full screen" `NnnPicker` always, only when it runs as a netrw replacement.
This result is what I'm looking for.

**Comment by luukvbaal** [comment]
If you don't intend to use `NnnExplorer` it makes more sense to set `NnnPicker` as `netrw` replacement indeed. I guess we can make `NnnPicker` cover the whole screen (set `width = height = 1`) under the same conditions that make NnnExplorer full screen, and use the configured dimensions otherwise.

**Comment by luukvbaal** [comment]
@anjerukare implemented in https://github.com/luukvbaal/nnn.nvim/commit/88627fbcb7309486dcbb81e452cf997aec94fddb.

**Comment by anjerukare** [comment]
> I guess we can make NnnPicker cover the whole screen (set width = height = 1) under the same conditions that make NnnExplorer full screen, and use the configured dimensions otherwise.

Was this idea rejected? Now with `replace_netrw = 'picker'` set, I have `NnnExplorer` without a split after entering file.

Also, with the current implementation, I'm missing `set number` after entering the file.

**Comment by luukvbaal** [comment]
> Was this idea rejected? Now with `replace_netrw = 'picker'` set, I have `NnnExplorer` without a split after entering file.

No that idea was implemented but instead of opening nnn inside of a floating window we open it inside the current window, making it fullscreen. That does not make it `NnnExplorer` though, it still closes after opening a single file(s). I didn't think opening a floating window would be necessary if we are going to be covering the full width/height anyways, do you disagree?


> Also, with the current implementation, I'm missing set number after entering the file.

Right we need to restore the buffer options after `NnnPicker` closes with the current implementation.

**Comment by anjerukare** [comment]
> What makes you call it NnnExplorer?

The status bar at the bottom and the spell checker. And I just realized that all of this can be disabled in my configuration. My bad 😓.

> I didn't think opening a floating window would be necessary if we are going to be covering the full width/height anyways, do you disagree?

No, that's right.

**Comment by luukvbaal** [comment]
> The status bar at the bottom and the spell checker.

Right, I guess that makes it different from a full size floating window. But yeah perhaps that's best left up to personal configuration. I will make sure to fix the buffer option problem then.

**Comment by luukvbaal** [comment]
> I'm missing `set number` after entering the file.

Should be fixed in latest commit.

**Comment by anjerukare** [comment]
> > I'm missing `set number` after entering the file.
> 
> Should be fixed in latest commit.

Yes, it is. Thanks!

I guess that for explorer netrw replacement this fix is also needed.
