### ISSUE TITLE
[BUG]: NnnPicker fails with invalid argument as env

### ISSUE THREAD

**Issue by StevenJPx2** [luukvbaal/nnn.nvim#63]
<img width="1290" alt="Screenshot 2022-08-05 at 9 44 48 AM" src="https://user-images.githubusercontent.com/33600496/183000317-66e6a157-21bd-4dbb-903f-a7590c937742.png">

When I run `NnnPicker`. `NnnExplorer` works fine.

**Comment by luukvbaal** [comment]
Please share your config, can't reproduce. Also `NnnExplorer` uses the same `env` argument so I don't get this bug.

**Comment by luukvbaal** [comment]
What is the value of your `TERM`?

**Comment by luukvbaal** [comment]
This error happens when your `TERM` is unset. Please make sure it is set accordingly in the cmd for `NnnPicker`.
