### ISSUE TITLE
nnn.nvim opens file in the previous window instead of the current one

### ISSUE THREAD

**Issue by itaranto** [luukvbaal/nnn.nvim#64]
Lets say I have 2 splits, if I open a file while being in split A, then the file is opened in split B.

This didn't happened before https://github.com/luukvbaal/nnn.nvim/commit/0fcc15a3c84d9d6de2ee0057bbcfb59386bf63ec.

**Comment by luukvbaal** [comment]
Could you please elaborate how to reproduce this? File opens in the correct split for me.

**Comment by itaranto** [comment]
https://user-images.githubusercontent.com/11463919/183102634-10fd3ed8-72d8-42f1-9359-8b4bdd39d360.mp4

**Comment by itaranto** [comment]
My config:

```lua
require('nnn').setup {
  picker = {
    style = {
      width = 0.8,
      height = 0.8,
      border = 'rounded',
    },
  },
  replace_netrw = 'picker',
}
```

**Comment by luukvbaal** [comment]
Thanks!

**Comment by itaranto** [comment]
> Thanks!

No problem!
