### ISSUE TITLE
starting nvim in a directory with NnnExplorer doesn't show an empty buffer anymore

### ISSUE THREAD

**Issue by FabioAntunes** [luukvbaal/nnn.nvim#65]
It seems that this has been changed recently not sure if on purpose or not.

Starting `nvim .` in a directory opens nnn in full screen, where before it would open in explorer mode with an empty buffer on the side

now:
![Screenshot 2022-08-16 at 10 26 26](https://user-images.githubusercontent.com/2544673/184846107-17b715fd-853f-442f-93a0-a256af9c0d5d.png)

before:
![Screenshot 2022-08-16 at 10 28 59](https://user-images.githubusercontent.com/2544673/184846574-7ad09881-f4ba-43ac-a868-1d006e96b78f.png)

**Comment by luukvbaal** [comment]
Indeed this change was intentional https://github.com/luukvbaal/nnn.nvim/issues/61. Logic being that when there is only an empty buffer, there is no reason for nnn to not be "fullscreen". Do you think we need an option to disable the behavior?

**Comment by FabioAntunes** [comment]
I will give you my use case.

I usually use `nvim .` for everything I'm always jumping around projects. 

The previous behaviour allows me to easily navigate, start editing some empty file.

I also have some key bindings that allow me to do fuzzy searching while on `nnn` when I do that, the empty buffer is used and replaced with the selection of my fuzzy searching. 

Unfortunately with the current behaviour when I fuzzy search it actually splits the screen in half instead of keeping the `nnn` in explorer mode.

This asciinema might be helpful for explaining the behaviour:

[![asciicast](https://asciinema.org/a/bkicMeEVf6D53MmLF8sPV1Cxm.svg)](https://asciinema.org/a/bkicMeEVf6D53MmLF8sPV1Cxm)

**Comment by FabioAntunes** [comment]
Maybe this is something that I can resolve on my side if there is a way to open a buffer and still keep the `nnn` in explorer mode?

When I run my fuzzy searching this what I do in my keybinding,

`map("t", "<leader>p", "<C-\\><C-N><CMD>vnew | Telescope find_files hidden=true<CR>", mapOpts)`

Is there a way for me to open a buffer as if it was `nnn` opening it and therefore it keeps `nnn` in explorer mode?

**Comment by luukvbaal** [comment]
I see, the problem is then indeed that is not nnn openeing the new window. If you are okay with nnnexplorer being fullscreen until a second window is opened, I guess we should be able to resize the explorer pane back to its configured width once nnn is no longer the only window. If you never want nnnexplorer to be fullscreen in the firstplace when running `nvim .` we will need a new option disabling the behavior.

**Comment by FabioAntunes** [comment]
Tested this and it works. thank you so much for the quick reply and quick fix, really appreciate the hard work.

**Comment by luukvbaal** [comment]
Thanks for reporting and confirming the fix👍🏻
