### ISSUE TITLE
nnn disables numbers and splits have different sizes

### ISSUE THREAD

**Issue by FabioAntunes** [luukvbaal/nnn.nvim#67]
Still related to this https://github.com/luukvbaal/nnn.nvim/issues/65

Since you have disabled having an empty buffer when starting `nvim .` `numbers` is set to false on the window level.

If I start `nvim .` I don't have `numbers` if I start `nvim some-random-file` and then open `nnn` everything is fine.

[![asciicast](https://asciinema.org/a/kwSVAxWrssh5yAfYx9rGfLDlQ.svg)](https://asciinema.org/a/kwSVAxWrssh5yAfYx9rGfLDlQ)

Another thing that I have noticed is that if I do `nvim .` then open a file, then do a `:vsplit` the splits aren't identical in size
![Screenshot 2022-09-14 at 09 58 13](https://user-images.githubusercontent.com/2544673/190109837-e70b9ce7-f49f-4daa-a8c7-e5a8526d4b14.png)

**Comment by luukvbaal** [comment]
Should be fixed in https://github.com/luukvbaal/nnn.nvim/commit/62b01532a9dcb0111459b308668aebdb0088bfd8.
