### ISSUE TITLE
Empty buffer opens when opening files from recently used list

### ISSUE THREAD

**Issue by medwatt** [luukvbaal/nnn.nvim#68]
I use [this](https://github.com/goolord/alpha-nvim) plugin to display the recently used files in vim during startup.

Opening a file directly (by pressing thr number displayed next to the file name) opens the file in a new buffer.

However, if I open `nnn` through this plugin, close it, and open a file just as before, an empty buffer is created.

While this is not a big issue, it's irritating to have to always close the empty buffer manually.

Here's a screen recording of the issue.

https://user-images.githubusercontent.com/17733465/191684351-35c2988d-fe13-41f3-968b-299bfeb1ddee.mp4

**Comment by luukvbaal** [comment]
Thanks for reporting. I have not tested your plugin, please confirm the fix.

**Comment by medwatt** [comment]
> Thanks for reporting. I have not tested your plugin, please confirm the fix.

Thanks for your quick reply. Unfortunately, the last fix did not resolve the issue. The empty buffer is still created.

**Comment by luukvbaal** [comment]
Using picker or explorer?

**Comment by medwatt** [comment]
> Using picker or explorer?

I'm using picker because I don't want the nnn window to persist.

**Comment by luukvbaal** [comment]
Was able to reproduce, I think this should fix it.

**Comment by medwatt** [comment]
> Was able to reproduce, I think this should fix it.

This fixes the issue when you (1) open picker (2) open a file from nnn. However if you (1) open picker (2) then exit picker without choosing a file, an empty buffer is still created.

Also, in your current solution, are you just closing the empty buffer after it opens or is the empty buffer not created entirely?

**Comment by luukvbaal** [comment]
> Also, in your current solution, are you just closing the empty buffer after it opens or is the empty buffer not created entirely?

I'm not sure where this buffer is coming from. It seems to be created on terminal exit by nvim when there is only an empty buffer. Please try the latest commit.

**Comment by medwatt** [comment]
> > Also, in your current solution, are you just closing the empty buffer after it opens or is the empty buffer not created entirely?
> 
> I'm not sure where this buffer is coming from. It seems to be created on terminal exit by nvim when there is only an empty buffer. Please try the latest commit.

The issue is now solved. Thanks !!
