### ISSUE TITLE
Unusual behaviour when using :NnnExplorer 

### ISSUE THREAD

**Issue by himanshugoswamiii** [luukvbaal/nnn.nvim#69]
I recently **updated all my plugins** after a long time and this started to happen

https://user-images.githubusercontent.com/96357852/192017292-a62e0934-dc64-4fad-b116-10d83467ceef.mp4

Everytime this extra buffer window pops up and I end with two `nnn` windows. 

When i close nnn, my previous file from which i was working was lost and this new empty buffer took its place.

`:NnnPicker` is working perfectly fine

**Comment by luukvbaal** [comment]
Yes, this was broken in a recent commit. Thanks for reporting!
