### ISSUE TITLE
Multiple nnn instances in various split windows (like netrw)

### ISSUE THREAD

**Issue by mxgrn** [luukvbaal/nnn.nvim#70]
Is there any way to open multiple nnn instances in various split windows?

When it would be helpful: when there's a need to watch multiple folders at once.

**Comment by luukvbaal** [comment]
Currently no. I'm not sure it will be worth the refactor required to support this either.

Does using nnn's contexts not suffice?

**Comment by mxgrn** [comment]
Not quite the same, no. Thanks for the answer!
