### ISSUE TITLE
Keybind custom nnn startup command

### ISSUE THREAD

**Issue by mattiasbonte** [luukvbaal/nnn.nvim#78]
Hello,

I wonder if its possible to for example 

'vim.keybind.set("n", "<C-f>", ":NnnExplorer({cmd="nnn -aP f"}))"'

or something which provides a similar way of binding a custom nnn command? 

I didn't really find it in the readme, but apologize if I missed it..

Thanks 🙏🏼

**Comment by luukvbaal** [comment]
Hey! A custom command is currently not possible. What is the use case you had in mind? If you just want to pass a path to nnn `NnnExplorer <path>` should work.

**Comment by mattiasbonte** [comment]
Hi luuk,

I'm used to using nnn for fuzzy finding dirs/files outside of nvim. But inside nvim I was always using telescope. And while that is perfect for the job. I notice that I really love the way folder movement goes with nnn. So I'd like to have that same functionality inside nvim.

For example
- I'd like to add a keymap to start nnn with the `fzopen` plugin already started to search files fast.
- But I'd also like a keymap to start a regular nnn instance as well without the `fzopen` plugin started.
So I would need to be able to add custom `nnn -P f` & `nnn` commands to 2 different keybinds. Preferably for the explorer. 

It would save me having to press `esc` whenever I open my explorer. Or having to press `;f`every time I open the explorer.


Shaving of milliseconds is vital after configuring an editor for weeks 👼🏼 🤣. What do you think?

While i'm at it. Maybe you as an nnn pro will know this, but I was wondering if there is a nnn plugin comparable to telescope's `live_grep` feature?

**Comment by luukvbaal** [comment]
I see, thanks for explaining. That does seem like it could be useful, I'll look into adding the feature.

I don't think we have a `live_grep` plugin. `finder` + `preview-tui` is as close as you're gonna get. But Telescope seems more suited for the job.

**Comment by luukvbaal** [comment]
Please check if https://github.com/luukvbaal/nnn.nvim/commit/d7138fbe8ba2831beaefa1a9abc9a064f5a25f4e works for you.

Quoting the README:

### Custom Command Argument

Additionally, passing `cmd=<custom command` as argument will override the configured nnn command. This allows you to for example run one-off nnn commands with different option flags. `:NnnExplorer cmd=nnn\ -Pf /mnt` will open explorer mode in `/mnt` and run the nnn plugin mapped to <kbd>f</kbd>. Spaces in the `cmd` string must be escaped.

**Comment by mattiasbonte** [comment]
Hi luuk,

Thanks again! I'm trying to get it working from within my lua config but with no success.

I'm using `vim.keymap.set("n", "<leader>f", "<cmd>NnnPicker cmd=nnn\ -Pf<cr>", { desc = "File Picker" })`.
I can't escape the space like so apparently, also tried to doulbe escape it..
vim.keymap.set("n", "<leader>f", "<cmd>NnnPicker cmd=nnn\\ -Pf<cr>", { desc = "File Picker" })
but also without success.

Any ideas?

**Comment by luukvbaal** [comment]
The second option works for me🤔 You could also try

    vim.keymap.set("n", "<leader>f", [[<cmd>NnnPicker cmd=nnn\\ -Pf<cr>]], { desc = "File Picker" })

What doesn't work, do you get an error?

**Comment by mattiasbonte** [comment]
I'm sorry it works indeed, I used `:source:` to try the change but that didn't work. Had to restart nvim. Cheers!
