### ISSUE TITLE
preselect file when using %:p:h

### ISSUE THREAD

**Issue by mattiasbonte** [luukvbaal/nnn.nvim#79]
Hey Luuk,

Do you think it be possible to preselect the current file when opening the explorer with the `NnnExplorer %:p:h` command?

Happy holidays. 🎁

**Comment by luukvbaal** [comment]
This should happen automatically. Though `%:p:h` expands to the containing directory of the current file. If you want to preselect the current file just use `%:p`. See `:h expand`.

**Comment by mattiasbonte** [comment]
Yes, thank you for the tip. `NnnExplorer %:p` does the trick. Much appreciated.

**Comment by luukvbaal** [comment]
Great, happy holidays to you too!
