### ISSUE TITLE
builtin.open_in_split opens first file in list and not selected.

### ISSUE THREAD

**Issue by Svenum** [luukvbaal/nnn.nvim#84]
I created a config like your template, but if i want to open a file with "C-s", "C-v", or "C-t" it opens the first element in the list and not the "hovered" one.

My config:
``` vim
" Options
lua << EOF
    local builtin = require("nnn").builtin
    require("nnn").setup({
        explorer = {
	            width = 40
	        },
        replace_netrw = nil,
        mappings = {
	             { "<C-s>", builtin.open_in_split },
	             { "<C-v>", builtin.open_in_vsplit },
	             { "<C-t>", builtin.open_in_tab },
             },
        auto_close = true,
        auto_open = {
                 setup = "picker",
                 tabpage = "pcker",
                 empty = true
            }
        
    })
EOF

"autocmd VimEnter * NnnExplorer
if @% != "" && @% != "." && @% != "./"
	autocmd VimEnter * execute  "normal \<C-w>\<right>" | stopinsert
endif

autocmd BufWinLeave,WinLeave term://* startinsert
" Functions
" Shortcuts
nnoremap <C-n> :NnnPicker<CR>
inoremap <C-n> <Esc> :NnnPicker<CR>
tnoremap <C-n> <C-\><C-n> :NnnPicker<CR>
```

**Comment by luukvbaal** [comment]
Hmm, I cannot reproduce this. It should open the hovered file or the active selection if it exists.

**Comment by Svenum** [comment]
Maybe the issue is somewhere else in my config:
https://github.com/Svenum/nvim-config

**Comment by luukvbaal** [comment]
Can you make a screen recording of your problem?

**Comment by Svenum** [comment]
https://user-images.githubusercontent.com/43136984/216831781-2c4ae653-eed9-41ea-9118-261598ab35d7.mp4

**Comment by luukvbaal** [comment]
I have no idea what could cause this sorry. If it is splitting the window, it must mean it is executing the mapping. Could you try adding a debug print statement?
```diff
+++ b/lua/nnn.lua
@@ -422,6 +422,7 @@ end
 local function open_in(files, command)
        for _, file in ipairs(files) do
                c(command.." "..file)
+               vim.pretty_print(command.." "..file)
        end
 end
```

**Comment by luukvbaal** [comment]
It should show up in `:messages` after using a mapping.

**Comment by luukvbaal** [comment]
But you should just add the single `pretty_print()` line to the existing `open_in()` function, not define a new function at the top of the file:
https://github.com/luukvbaal/nnn.nvim/blob/440ddfd4b41315355b5ec7911b9559bc73165b8b/lua/nnn.lua#L421-L426

**Comment by Svenum** [comment]
I got the output:
"vsplit /home/user/test/nnn-test/cloud.txt"
(vsplit first item in the list and not hovered)

**Comment by luukvbaal** [comment]
I don't understand how it could happen, there must be something interfering. Can you try this in `NnnExplorer` instead? That way you should be able to see what actually happens in the terminal window as it stays open.

**Comment by luukvbaal** [comment]
Is it really switching to the first item in a directory with more than two files? Or perhaps just the file above it? The mapping must be feeding either a <kbd>g</kbd>, or <kbd>k</kbd> key somehow.

**Comment by luukvbaal** [comment]
Can you check if this fixes the issue?

```diff
+++ b/lua/nnn.lua
@@ -221,14 +221,15 @@ local function buffer_setup()
                a.nvim_buf_set_option(0, opt, val)
        end

+       local opts = { noremap = true }
        for i, mapping in ipairs(cfg.mappings) do
-               a.nvim_buf_set_keymap(0, "t", mapping[1], "<C-\\><C-n><cmd>lua require('nnn').handle_mapping("..i..")<CR>", {})
+               a.nvim_buf_set_keymap(0, "t", mapping[1], "<C-\\><C-n><cmd>lua require('nnn').handle_mapping("..i..")<CR>", opts)
        end

-       a.nvim_buf_set_keymap(0, "t", cfg.windownav.left, "<C-\\><C-n><C-w>h", {})
-       a.nvim_buf_set_keymap(0, "t", cfg.windownav.right, "<C-\\><C-n><C-w>l", {})
-       a.nvim_buf_set_keymap(0, "t", cfg.windownav.next, "<C-\\><C-n><C-w>w", {})
-       a.nvim_buf_set_keymap(0, "t", cfg.windownav.prev, "<C-\\><C-n><C-w>W", {})
+       a.nvim_buf_set_keymap(0, "t", cfg.windownav.left, "<C-\\><C-n><C-w>h", opts)
+       a.nvim_buf_set_keymap(0, "t", cfg.windownav.right, "<C-\\><C-n><C-w>l", opts)
+       a.nvim_buf_set_keymap(0, "t", cfg.windownav.next, "<C-\\><C-n><C-w>w", opts)
+       a.nvim_buf_set_keymap(0, "t", cfg.windownav.prev, "<C-\\><C-n><C-w>W", opts)
 end

  -- Restore buffer to previous state
```

**Comment by Svenum** [comment]
If I add this i get this error:
```
E5108: Error executing lua vim/_init_packages.lua:0: .../sven/.config/nvim/autoload/plugged/nnn.nvim/lua/nnn.lua:224: unexpe
cted symbol near '{'
stack traceback:
        [C]: in function 'error'
        vim/_init_packages.lua: in function <vim/_init_packages.lua:0>
        [C]: in function 'require'
        [string ":lua"]:1: in main chunk
E325: ATTENTION
```

**Comment by Svenum** [comment]
It resolved it :)

**Comment by Svenum** [comment]
What does this change do?

**Comment by luukvbaal** [comment]
It uses the non-recursive `:h tnoremap` instead of the `:h tmap` command. Meaning that it will use internal vim mappings rather than potential user-defined mappings. I should have included that from the start.
