### ISSUE TITLE
Plugins not usable within tmux session cmd override

### ISSUE THREAD

**Issue by ConnorWay32** [luukvbaal/nnn.nvim#86]
I followed the advice in the readme for having preview-tui show up in the picker window, by setting the command to `tmux new-session nnn -P<plugin key>`, but found that no plugins were showing up when I pressed p. Using NNN's command prompt, I tried `echo $NNN_PLUG`, but that returned a blank value. The same command returns the correct value when using the default cmd for the picker.
`which nnn` returned the same address in both cases. The tmux override command returned the same empty environment variable and address whether Neovim was running inside a tmux session or not.

preview-tui and other plugins worked correctly when using nnn from the terminal, nnn with the default picker cmd, nnn inside a tmux session inside a ToggleTerm floating window, and nnn inside a tmux session inside a tmux floating window.

**Comment by luukvbaal** [comment]
Well you just need to make sure `NNN_PLUG` is exported in the tmux environment. I set environment variables in my `~/.(z)profile`, that works.

**Comment by ConnorWay32** [comment]
Thanks, that worked.
