### ISSUE TITLE
barbar buffer line lists nnn buffer momentarily

### ISSUE THREAD

**Issue by medwatt** [luukvbaal/nnn.nvim#87]
I have using a buffer bar that shows all the buffers currently open. Whenever I open `nnn` using `NnnPicker`, I see a temporary buffer open quickly and gets removed installed (see image below). I don't know if this is a bug, but should this be happening?

![img](https://i.imgur.com/31Ie1Gw.png)

**Comment by luukvbaal** [comment]
I'm not sure what I'm looking at. Are you talking about the `nnn -p /tmp/...` buffer? That's just the terminal buffer nnn requires, perhaps it is hidden later by your buffer bar filter?

I don't think this plugin creates unnecessary buffers.

**Comment by medwatt** [comment]
When I open a floating terminal with [voldikss/vim-floaterm](https://github.com/voldikss/vim-floaterm), a floating terminal opens without creating any entry in the buffer bar. However, when using this plugin, an entry is momentarily created. Hence my question.

**Comment by medwatt** [comment]
Please have a look at these screenshots [here](https://imgur.com/a/UJVzRSV).

**Comment by luukvbaal** [comment]
The number of buffers is the same?

**Comment by medwatt** [comment]
Yes, when I open a floating terminal, it gets registered in the buffer bar momentarily, whereas it doesn't with floaterm.

**Comment by luukvbaal** [comment]
Like I said, I would sooner accredit to your buffer bar filters rather than something that floaterm does differently.

**Comment by medwatt** [comment]
Adding `nnn` to `exclude_ft` doesn't do anything.

**Comment by luukvbaal** [comment]
I'll look into it when I get the time, I don't have this problem with https://github.com/akinsho/bufferline.nvim...

**Comment by luukvbaal** [comment]
Was able to reproduce and fix. I guess my buffer line plugin checks `'buflisted'` later.
