### ISSUE TITLE
NnnPicker doesn't show the last time of nnn

### ISSUE THREAD

**Issue by medwatt** [luukvbaal/nnn.nvim#88]
I don't know if this is a neovim bug or an `nnn.nvim` bug, but when I open `nnn` through `NnnPicker`, the bottom line of nnn doesn't show.

This is `nnn` opened directly from the terminal. Notice that the bottom line shows correctly.

![image](https://user-images.githubusercontent.com/17733465/230296144-64a715e0-f525-4962-8988-d3a16dce615c.png)

This is `nnn` opened through `NnnPicker`l. Notice that the bottom line is not showing.

![image](https://user-images.githubusercontent.com/17733465/230295664-0bd24324-9096-48f3-99bb-2635ff92dedc.png)

**Comment by luukvbaal** [comment]
Not sure, the bottom line shows fine for me when `nnn'nvim` is in fullscreen. Gonna need a way to reproduce this...

**Comment by medwatt** [comment]
> Not sure, the bottom line shows fine for me when `nnn.nvim` is in fullscreen. Gonna need a way to reproduce this...

Just figured out that this is a problem with the latest neovim nightly. I switched back to v0.8.3 and the problem went away. Have a look at the latest nightly and you will be able to reproduce the bug.

**Comment by luukvbaal** [comment]
> Have a look at the latest nightly and you will be able to reproduce the bug.

I tested on nightly initially, I'm not seeing it. You should provide a minimal reproducible config when making a claim like this on an issue report.

**Comment by luukvbaal** [comment]
OK, reproduced it.

**Comment by luukvbaal** [comment]
Should be fixed, thanks for reporting.
