### ISSUE TITLE
Enter / Return doesn't work in explorer mode but in picker mode

### ISSUE THREAD

**Issue by rafo** [luukvbaal/nnn.nvim#91]
Pressing <cr> on a file doesn't do anything. But it works when nnn is started in picker mode.
Pressing <cr> normal mode in a file in nvim acts like pressing j.

My nnn config. I am using [lazyvim](https://www.lazyvim.org/) with wezterm.

My config is simple:

```
return {
  "luukvbaal/nnn.nvim",
  opts = {
    explorer = {
      -- cmd = "nnn -AcDH", -- command overrride (-F1 flag is implied, -a flag is invalid!)
      cmd = "nnn -GH",
      width = 36, -- width of the vertical split
      side = "topleft", -- or "botright", location of the explorer window
      -- session = "shared", -- or "global" / "local" / "shared"
      session = "",
      tabs = true, -- seperate nnn instance per tab
      fullscreen = true, -- whether to fullscreen explorer window when current tab is empty
    },
    picker = {
      cmd = "nnn -aAcDH", -- command override (-p flag is implied)
      style = {
        width = 0.7, -- percentage relative to terminal size when < 1, absolute otherwise
        height = 0.7, -- ^
        xoffset = 0.5, -- ^
        yoffset = 0.5, -- ^
        border = "single", -- border decoration for example "rounded"(:h nvim_open_win)
      },
      session = "", -- or "global" / "local" / "shared"
      fullscreen = true, -- whether to fullscreen picker window when current tab is empty
    },
    auto_open = {
      -- setup = "explorer", -- or "explorer" / "picker", auto open on setup function
      -- tabpage = "explorer", -- or "explorer" / "picker", auto open when opening new tabpage
      -- empty = true, -- only auto open on empty buffer
      ft_ignore = { -- dont auto open for these filetypes
        "gitcommit",
      },
    },
    -- buflisted = false, -- whether or not nnn buffers show up in the bufferlist
    -- quitcd = nil, -- or "cd" / tcd" / "lcd", command to run on quitcd file if found
    -- windownav = { -- window movement mappings to navigate out of nnn
    --   left = "<C-w>h",
    --   right = "<C-w>l",
    --   next = "<C-w>w",
    --   prev = "<C-w>W",
    -- },
  },
}
```

:checkhealth 

```
﻿﻿which-key: require("which-key.health").check()

WhichKey: checking conflicting keymaps ~
- WARNING conflicting keymap exists for mode **"n"**, lhs: **"gc"**
- rhs: ` 
```

:version
```
NVIM v0.9.1
Build type: Release
LuaJIT 2.1.0-beta3

          System-vimrc-Datei: "$VIM/sysinit.vim"
     $VIM: "/opt/homebrew/Cellar/neovim/0.9.1/share/nvim"
```
.zshenv
```
# NNN
#export NNN_COLORS='4321'
# export NNN_FCOLORS='c1e2272e006033f7c6d6abc4'
export NNN_FIFO='/Users/rafael/.local/share/nnn/nnn.fifo'
export NNN_PLUG='f:finder;o:fzopen;p:preview-tabbed;v:imgview;g:getplugs;s:! echo $nnn|xclip*'
export NNN_PREVIEWDIR='/Users/bingo/.local/share/nnn/preview/'
#export NNN_TRASH=1 # use desktop Trash
export NNN_TMPFILE='/Users/bingo/.local/share/nnn/nnn.lastd' # always cd on quit

```

I tested it on kitty and the default macOS terminal, but explorer mode doesn't work in those terminals and I don't know why???

**Comment by rafo** [comment]
When I change `tabs = true` to `false`, explorer mode doesn't work.

**Comment by luukvbaal** [comment]
I saw an error when `tabs == false` which I fixed in the latest commit, did you not see this?
Please confirm your issue is fixed.

**Comment by rafo** [comment]
Updated right now:

nnn.nvim 6.69ms  start
        c3e00b3 fix: nil index when cfg.explorer.tabs is false

the tabs = false problem is gone. The _Return Problem_ is still there. ;D

**Comment by luukvbaal** [comment]
I'm not sure why Enter / Return wouldn't work. Perhaps you are not in terminal mode, could you send a screenshot? Or just try pressing "i" first, if that solves it you should check what in your config makes you leave terminal mode.

**Comment by rafo** [comment]
[![asciicast](https://asciinema.org/a/eAYvJPIaB7efsJjptBIp2dmKr.svg)](https://asciinema.org/a/eAYvJPIaB7efsJjptBIp2dmKr)

Since the picker works, I am not sure how I can be not in _terminal mode_. 
I tested zsh without vim mode, but that doesn't change anything. The tabs = false problem is gone, Explorer Mode works now in kitty and macOS terminal.

I will restart my Mac without any zshenv and zshrc – ...

**Comment by luukvbaal** [comment]
Yeah no doesn't look like terminal mode is the issue. You could try adding debug `print()` statements to `read_fifo()` or `handle_files()` if that even gets called.

**Comment by rafo** [comment]
It looks like a restart without my zshenv and zshrc fixed the problem. I will locate the malicious setting and keep you updated. Maybe something is hijacking _return_ in Explorer Mode. 

Interesting.

**Comment by rafo** [comment]
Just to keep you informed:
1. Merged my env and rc
2. Removed all alias.
3. Test: return works!
4. Enabled alias files one by one and tested every time until all aliases are enabled again: return still works!
5. Insert surprised_pikachu.jpg

So… maybe a zsh hiccup… cache… I don't know.

**Comment by JefeDavis** [comment]
just in case anybody else runs into this, if you have NNN_FIFO set already, you will hit this issue. use `-a` instead of setting a global NNN_FIFO variable if you need fifo, i spent way more time then i care to admit scratching my head on this one
