### ISSUE TITLE
Honor the NNN_SEL env var

### ISSUE THREAD

**Issue by mapperr** [luukvbaal/nnn.nvim#92]
Hi!

I was wandering if nnn.nvim can consider the NNN_SEL env var like it do with NNN_FIFO and NNN_OPTS.

Sometimes I want to run commands on a selection and I can find handy to have my custom selection file on nnn.nvim.

**Comment by mapperr** [comment]
Dunno, the thing is NNN_SEL is exported but if I use NnnPicker, select some files and trigger a shell with "!" I see this:

```
archbox> % echo $NNN_SEL 
/tmp/.nnnsel
archbox> % cat $NNN_SEL
cat: /tmp/.nnnsel: No such file or directory
```
If I do the same with normal nnn (i.e. not with this nvim plugin) things are as expected, I get the selection written in that selection file.

Then I thought that maybe it has something to do with the plugin

(sorry, I should've said this sooner ^^' )

**Comment by luukvbaal** [comment]
Hmm yeah I can reproduce that behavior, not sure what's causing that.

**Comment by luukvbaal** [comment]
Oh right, `nnn` doesn't write to the selection file if picker mode is enabled. Not sure if it is reasonable to request that over on the `nnn` issue tracker.

So in the context of this plugin, `NnnExplorer` will pick up `$NNN_SEL` and write to it accordingly, `NnnPicker` won't.
