### ISSUE TITLE
No possible ways to remap quit from Picker/Explorer keybind

### ISSUE THREAD

**Issue by LoliPain** [luukvbaal/nnn.nvim#94]
Environment:

- ❯ nnn -V
        4.4

- ❯ nvim -ver
        NVIM v0.9.1

- nnn.nvim (latest commit)

Using this in my .lua config
```lua
local remaper = vim.api.nvim_set_keymap
local noremap = { noremap = true, silent = true }

-- Open nnn using \\
remaper('n', '<leader><leader>', ':NnnPicker %:p:h<CR>', noremap)
```

AFAIK, there's not available to remap quit from NnnPicker (same as Explorer) bind, so that's kinda annoying using default 'q' mapping.
In my case (i guess other will agree), that using the same keybind produced for executing nnn will be way more useful that pre-defined one

**Comment by luukvbaal** [comment]
You need to map `NnnPicker/Explorer` also in terminal mode:

```lua
-- Toggle nnn using \\
remaper({'n', 't'}, '<leader><leader>', ':NnnPicker %:p:h<CR>', noremap)
```

Then the same key can be used to toggle nnn (closing it will close the window, not the nnn instance).

**Comment by LoliPain** [comment]
> ```lua
> remaper({'n', 't'}, '<leader><leader>', ':NnnPicker %:p:h<CR>', noremap)
> ```

those wouldn't work due to remaper in my case defined as `vim.api.nvim_set_keymap`, where is intended to use only short-name of one vim mode

> Parameters:
{mode} Mode short-name (map command prefix: "n", "i", "v", "x", …) or "!" for [:map!](https://neovim.io/doc/user/map.html#%3Amap%21), or empty string for [:map](https://neovim.io/doc/user/map.html#%3Amap). "ia", "ca" or "!a" for

but if i would remap it using `vim.keymap.set` which is supports multiple modes at one.
but for now i'm getting `failed!` message at the picker's bottom statusline 
same as using two separate `nvim_set_keymap` calls
 ```lua
-- Open nnn using \\
remaper('n', '<leader><leader>', ':NnnPicker %:p:h<CR>', noremap)
-- CLose nnn using \\
remaper('t', '<leader><leader>', ':NnnPicker %:p:h<CR>', noremap)

```

**Comment by LoliPain** [comment]
i used something like that
```lua
remaper('n', '<leader><leader>', ':NnnPicker %:p:h<CR>', noremap)
remaper('t', '<leader><leader>', 'q', noremap)
```
but tbh i guess it's workaround and not how it's meant to be

**Comment by luukvbaal** [comment]
TBH I'm not sure what you're working around, I don't see the "failed!" message.
Most correct imo would be:

```lua
vim.keymap.set("n", "<leader><leader>", "<cmd>NnnExplorer %:p:h<CR>")
vim.keymap.set("t", "<leader><leader>", "<cmd>NnnExplorer<CR>")
```

**Comment by LoliPain** [comment]
it works properly now, thanks!
