### ISSUE TITLE
NNN with tmux does not show hidden files in the preview window

### ISSUE THREAD

**Issue by rensftw** [luukvbaal/nnn.nvim#95]
**Environment:**
- NNN: `v4.8`
- Nvim:  `v0.9.1`
- nnn.nvim commit: 4616ec65eb0370af548e356c3ec542c1b167b415

By default my `nnn.nvim` config for `:NnnPicker` specifies that hidden files should be shown:

```lua
require('nnn').setup({
    picker = {
        style = {
            border = 'rounded'
        },
        -- -a: auto-setup temporary NNN_FIFO
        -- -d: detail mode
        -- -H: show hidden files
        -- -P: specify plugin key to run
        cmd = 'tmux new-session nnn -a -d -H -P=preview-tui',
        session = 'shared',
        fullscreen = false,
    },
})
```

However, the preview window does not show hidden files or directories here's an example directory:
```
~/.dotfiles/nvm
├── .nvm
│   └── default-packages
└── .test.txt

2 directories, 2 files
```

1. Preview of parent (`~/.dotfiles`):
<img width="1496" alt="image" src="https://github.com/luukvbaal/nnn.nvim/assets/22574186/a91636ce-c0dc-43dc-91dd-c57473776710">

2. Navigating inside `~/.dotfiles/nvm` shows hidden files in the NNN window
<img width="1496" alt="image" src="https://github.com/luukvbaal/nnn.nvim/assets/22574186/6e45c348-160c-41e2-8192-6fd65e4d2ada">

**Comment by luukvbaal** [comment]
This is not an issue with nnn.nvim. What is shown in the preview pane is determined by the directory preview program used in `preview-tui`. In your case it looks like that is `tree`. You could opt to add the `-a` flag to the `tree` command used by `preview-tui`.

**Comment by luukvbaal** [comment]
I also seem to remember nnn adding a `NNN_INCLUDE_HIDDEN` envvar at some point. I think the point was to keep it in sync with nnn's hidden file toggle. Perhaps support for that could be added to `preview-tui`.
