### ISSUE TITLE
Setting NNN_FIFO variable breaks NnnExplorer

### ISSUE THREAD

**Issue by nimaaskarian** [luukvbaal/nnn.nvim#97]
I was wondering why NnnExplorer isn't opening any files for me. I unset some of my variables, and found out it was the NNN_FIFO variable setting (I had it set to /tmp/nnn.fifo) breaks the NnnExplorer.

**Comment by luukvbaal** [comment]
This plugin sets the NNN_FIFO environment variable and should overwrite any that may be set in the current env. If that is not the case please provide steps on how to reproduce. But yes if you're somehow overwriting the value set by this plugin then it is expected that NnnExplorer will not work.

**Comment by nimaaskarian** [comment]
Oh. Thanks for the notice. I was "somehow overwriting the value" as you said. Sourcing my nnn_variables file in cmd option of the explorer. Fixed by removing it.
And also, thanks for the awesome plugin!
