### ISSUE TITLE
Padding around border in neovim 0.10

### ISSUE THREAD

**Issue by medwatt** [luukvbaal/nnn.nvim#99]
I recently updated to neovim 0.10 from 0.95. I notice that there's now an uneven padding in the top and bottom of the floating frame which gives an unpleasing aesthetic (see image below). This issue was not present in neovim 0.95.

![image](https://github.com/luukvbaal/nnn.nvim/assets/17733465/6b811e0a-5241-41fe-9114-28c3a2409120)

**Comment by luukvbaal** [comment]
The border can be configured through the `NnnBorder` highlight group, which links to `FloatBorder` by default. Neovim 0.10 ships with a new default colorscheme, which presumably sets `FloatBorder` to this color you see.

**Comment by medwatt** [comment]
Thanks for the reply. Do you have an example how to configure it?

**Comment by luukvbaal** [comment]
Oh, I'm not sure what you mean with uneven padding. All I see in your image is a black border, which is (expectedly) taller than it is wide as it is a terminal cell. You can "hide" it by linking the FloatBorder group to Normal.

**Comment by medwatt** [comment]
This is how it looks in neovim 0.9.5.

![image](https://github.com/luukvbaal/nnn.nvim/assets/17733465/8812e89a-72c4-44bd-b908-f73305119d98)

This is how it looks now:

![image](https://github.com/luukvbaal/nnn.nvim/assets/17733465/021f0c1a-e6ac-4088-94d6-8236fa60a357)

**Comment by medwatt** [comment]
I think I fixed the issue. I had to manually set the highlight since my colorscheme did not support it.

```
vim.api.nvim_set_hl(0, 'FloatBorder', { fg = fg, bg = bg })
```
